Update sync.yml

diff --git a/.github/workflows/sync.yml b/.github/workflows/sync.yml
--- a/.github/workflows/sync.yml
+++ b/.github/workflows/sync.yml
@@ -1,4 +1,7 @@
-name: Sync Upstream
+name: Upstream Sync
+
+permissions:
+  contents: write
 
 on:
   schedule:
@@ -6,17 +9,33 @@ on:
   workflow_dispatch: # 点击按钮手动触发
 
 jobs:
-  sync:
+  sync_latest_from_upstream:
+    name: Sync latest commits from upstream repo
     runs-on: ubuntu-latest
+    if: ${{ github.event.repository.fork }}
+
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
+      # Step 1: run a standard checkout action
+      - name: Checkout target repo
+        uses: actions/checkout@v3
+
+      # Step 2: run the sync action
+      - name: Sync upstream changes
+        id: sync
+        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
         with:
-          ref: 'master'  # 如果你的默认分支是main，请将此处的master替换为main
-      - name: Sync with upstream
+          upstream_sync_repo: gaotianliuyun/gao  # 修改为你想要同步的目标仓库
+          upstream_sync_branch: master  # 修改为你想要同步的上游仓库分支
+          target_sync_branch: master  # 修改为你想要同步到的目标仓库分支
+          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
+
+          # 设置 test_mode 为 true 可以只运行测试而不实际执行同步操作
+          test_mode: false
+
+      - name: Sync check
+        if: failure()
         run: |
-          git remote add upstream https://github.com/gaotianliuyun/gao.git
-          git fetch upstream
-          git merge upstream/master --allow-unrelated-histories
-          # 如果使用的是main分支，将上面的master替换为main
-          git push
+          echo "[Error] 由于上游仓库的 workflow 文件变更，导致 GitHub 自动暂停了本次自动更新，你需要手动 Sync Fork 一次，详细教程请查看：https://github.com/gaotianliuyun/gao/blob/main/README_CN.md#%E6%89%93%E5%BC%80%E8%87%AA%E5%8A%A8%E6%9B%B4%E6%96%B0"
+          echo "[Error] Due to a change in the workflow file of the upstream repository, GitHub has automatically suspended the scheduled automatic update. You need to manually sync your fork. Please refer to the detailed tutorial for instructions: https://github.com/gaotianliuyun/gao#enable-automatic-updates"
+          exit 1
+
